apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: gatekeeper
spec:
  interval: 10m
  url: https://open-policy-agent.github.io/gatekeeper/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gatekeeper
spec:
  interval: 1m
  chart:
    spec:
      chart: gatekeeper
      version: v3.2.2
      sourceRef:
        kind: HelmRepository
        name: gatekeeper
  values:
    logLevel: INFO
